### ISSUE TITLE
sinon not properly loaded in browser

### ISSUE THREAD

**Issue by anderspitman** [tidepool-org/salinity#1]
This is a fun one. While trying to get blip passing 100% of the current tests there is currently a problem with sinon in `navbar.test.js`.

For the basics of the problem you can reference [this SO question](http://stackoverflow.com/q/20570301/943814) as well as the one I asked and answered [here](http://stackoverflow.com/q/25333595/943814).

What it boils down to is sinon has a bunch of submodules (such as spy, stub, mock, etc) which it depends on. When loading in node, sinon.js automatically pulls these in. However, in the browser (using [AMD](http://en.wikipedia.org/wiki/Asynchronous_module_definition)) with the version of sinon we are using (1.8.3) you have to do it manually. It looks like newer versions of sinon automatically do it for AMD but I tried it and webpack complains about the way require is used and doesn't work.

So, if we stick with the current version of sinon, the solution from my SO answer _does work_, but seems a bit messy to me. I can make a PR, but wanted to see what thoughts and/or solutions others might have.

**Comment by darinkrauss** [comment]
Will not fix.
